/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (4.3.1).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.api;

import org.openapitools.model.InlineObject29;
import org.openapitools.model.InlineObject30;
import org.openapitools.model.InlineObject31;
import org.openapitools.model.InlineResponse20032;
import org.openapitools.model.InlineResponse20033;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.CookieValue;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2023-06-06T16:31:21.921210200+08:00[Asia/Shanghai]")

@Validated
@Api(value = "center", description = "the center API")
public interface CenterApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * POST /center/modifyPassword : 修改密码
     *
     * @param token 用户鉴权 (optional)
     * @param inlineObject31  (optional)
     * @return 成功 (status code 200)
     */
    @ApiOperation(value = "修改密码", nickname = "centerModifyPasswordPost", notes = "", response = InlineResponse20033.class, tags={ "center", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "成功", response = InlineResponse20033.class) })
    @RequestMapping(value = "/center/modifyPassword",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    default ResponseEntity<InlineResponse20033> centerModifyPasswordPost(@ApiParam(value = "用户鉴权" ) @RequestHeader(value="token", required=false) String token,@ApiParam(value = ""  )  @Valid @RequestBody(required = false) InlineObject31 inlineObject31) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"status_code\" : true }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /center/modifyUserInformation : 修改个人信息
     *
     * @param token 用户鉴权 (optional)
     * @param inlineObject30  (optional)
     * @return 成功 (status code 200)
     */
    @ApiOperation(value = "修改个人信息", nickname = "centerModifyUserInformationPost", notes = "", response = InlineResponse20033.class, tags={ "center", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "成功", response = InlineResponse20033.class) })
    @RequestMapping(value = "/center/modifyUserInformation",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.POST)
    default ResponseEntity<InlineResponse20033> centerModifyUserInformationPost(@ApiParam(value = "用户鉴权" ) @RequestHeader(value="token", required=false) String token,@ApiParam(value = ""  )  @Valid @RequestBody(required = false) InlineObject30 inlineObject30) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"status_code\" : true }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /center/personInformation : 个人中心信息
     *
     * @param token 用户鉴权 (optional)
     * @param inlineObject29  (optional)
     * @return 成功 (status code 200)
     */
    @ApiOperation(value = "个人中心信息", nickname = "centerPersonInformationGet", notes = "", response = InlineResponse20032.class, tags={ "center", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "成功", response = InlineResponse20032.class) })
    @RequestMapping(value = "/center/personInformation",
        produces = { "application/json" }, 
        consumes = { "application/json" },
        method = RequestMethod.GET)
    default ResponseEntity<InlineResponse20032> centerPersonInformationGet(@ApiParam(value = "用户鉴权" ) @RequestHeader(value="token", required=false) String token,@ApiParam(value = ""  )  @Valid @RequestBody(required = false) InlineObject29 inlineObject29) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"userPhone\" : \"userPhone\", \"stationName\" : \"stationName\", \"startTime\" : \"startTime\", \"userEmail\" : \"userEmail\", \"userName\" : \"userName\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
